version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - run: ./echo_new_file.sh
      - store_test_results:
        path: /tmp
      - run: bash <(curl -s https://install.meteor.com)
      - node/with-cache:
          steps:
            - run: npm install
      - run: meteor npm test