version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - run: bash <(curl -s https://install.meteor.com)
      - run: npm install
      - run: mkdir /tmp/artifacts
      - run: MOCHA_REPORTER=xunit SERVER_MOCHA_OUTPUT=/tmp/artifacts/unit_server.xml CLIENT_MOCHA_OUTPUT=/tmp/artifacts/unit_client.xml meteor test --once --driver-package meteortesting:mocha
      
      - store_test_results:
        path: /tmp/artifacts
        when: always
      
      # - store_artifacts:
      #   path: /tmp/artifacts
