version: 2.1
orbs:
  node: circleci/node@3.0.0
# workflows:
#   workflow:
#     version: 1
#     "basic test":
jobs:
  build:
    docker:
      - image: circleci/node@3.0.0
    steps:
      - run:
        command: curl https://install.meteor.com | /bin/sh
  install:
    docker:
      - image: circleci/node@3.0.0
  #   steps:
  #     - run:
  #       command: npm install
  # # test:
  #   docker:
  #     - image: circleci/node@3.0.0
  #   steps:
  #     - run:
  #       command: meteor npm test

workflows:
  build_and_test:
    jobs:
      - build
      # - install
      # - test:
      #     requires:
      #       - build