version: 2.1
orbs:
  node: circleci/node@3.0.0
# workflows:
#   workflow:
#     version: 1
#     "basic test":
jobs:
  steps:
    - run:
      command: curl https://install.meteor.com | /bin/sh
    - run:
      command: npm install
    - run:
      command: meteor npm test
