version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - run: echo "<note>
<to>Tove</to>
<from>Jani</from>
<heading>Reminder</heading>
<body>Don't forget me this weekend!</body>
</note> >> 'tmp'"
      - store_test_results:
        path: /tmp/test-results
      - run: bash <(curl -s https://install.meteor.com)
      - node/with-cache:
          steps:
            - run: npm install
      - run: meteor npm test