version: 2.1
orbs:
    node: circleci/node@1.1
jobs:
    prepare:
        executor:
            name: node/default
            tag: '10.4'
        steps:
        - checkout
        - run: bash <(curl -s https://install.meteor.com)
        - run: npm install
        # - run: meteor npm i --save-dev selenium-webdriver@^3.6.0 chromedriver@^2.41.0
        - run: npm i --save-dev phantomjs-prebuilt
        - run: meteor npm install --save bcrypt
        - run: mkdir /tmp/artifacts
        - run:
            name: execute meteor test
            command: MOCHA_REPORTER=xunit TEST_BROWSER_DRIVER=phantomjs SERVER_MOCHA_OUTPUT=/tmp/artifacts/unit_server.xml  CLIENT_MOCHA_OUTPUT=/tmp/artifacts/unit_client.xml  meteor test --once --driver-package meteortesting:mocha #> /tmp/artifacts/client
            when: always
        - store_artifacts:
            path: /tmp/artifacts
            when: always
         
    save:
        executor:
            name: node/default
            tag: '10.4'
        steps:
            - checkout
            - run:
                name: purify console output
                command: ./create_client.sh /tmp/artifacts/client /tmp/artifacts/unit_server.xml
            - store_test_results:
                path: /tmp/artifacts
            - store_artifacts:
                path: /tmp/artifacts
                when: always
        
workflows:
    version: 2.1
    build:
        jobs:
            - prepare
            - save:
                requires:
                    - prepare
        
