version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - run: bash <(curl -s https://install.meteor.com)
      - run: npm install
      - run: mkdir ~/tmp
      - run: meteor test --once --driver-package meteortesting:mocha
      # - store_test_results:
      #   path: $PWD/tmp
      # - store_artifacts:
      #   path: $PWD/tmp
