version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - run: bash <(curl -s https://install.meteor.com)
      - node/with-cache:
          steps:
            - run: npm install
      - run: MOCHA_REPORTER=xunit SERVER_MOCHA_OUTPUT=$PWD/tmp/unit_server.xml CLIENT_MOCHA_OUTPUT=$PWD/tmp/unit_client.xml meteor test --once --driver-package meteortesting:mocha
      - store_test_results:
        path: $PWD/tmp
      - store_artifacts:
        path: $PWD/tmp
